development:
  adapter: postgresql
  encoding: unicode
  database: crud-review1_development
  pool: 5
  username: user
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: crud-review1_test
  pool: 5
  username: user
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: crud-review1_production
  pool: 5
  username: user
  password:
  host: localhost
